### ISSUE TITLE
Jellyfish galaxy

### ISSUE THREAD

**Issue by nrgolovich** [karenyyng/MACSJ1752#1]
The redshift is 0.372684.

It is slit 82 of mask mc171B in case anyone wants to look at the spectrum. I would, but I still haven't updated my idl backend after Will moved the reduction files to github. 

I did the zspec for this mask and my comment was: Hb, Mgb, NaD, Hd, Gband, OIII, rc

But this was before I was smart enough to say Hb em versus Hb ab. Although, the fact that there is a rotation curve (rc), means that these are probably emission lines.

**Comment by karenyyng** [comment]
@wadawson , great that Nate found the jellyfish galaxy :+1:. What type of analyses can we do with it?

**Comment by nrgolovich** [comment]
@karenyyng @wadawson Just saw that this exact galaxy is in Table 1 of 
http://arxiv.org/pdf/1312.6135v2.pdf

Bottom right image in figure 2. Ebeling didn't quote a redshift of this galaxy in particular in this paper.

**Comment by wadawson** [comment]
Here are the 1D and 2D spectra. Unfortunately this was before we started trying to capture both Hb and Ha. I am imaging David Sobral can tell us something from the spectrum.

@nrgolovich good catch on the archive paper. This paper is part of the reason I got excited about the galaxy, I just didn't realize that this galaxy was actually in the paper.

![macs1752_slit82_1d](https://cloud.githubusercontent.com/assets/3067471/6499052/65a69516-c2a9-11e4-8385-eb1144ebffea.png)

![macs1752_slit82_2d](https://cloud.githubusercontent.com/assets/3067471/6499050/603e74cc-c2a9-11e4-8d57-d2f9f9a2a8f8.png)

**Comment by nrgolovich** [comment]
@wadawson  Interesting that the OIII emission lines aren't stronger. From what I've seen in the past while looking at spectra, OIII lines are typically bright when Ha/Hb emission is present. 

Also, if these jellyfish galaxies are supposed to have a lot of star formation, shouldn't we expect Hd to be emission too rather than absorption like it is. I've seen some spectra where all of the balmer lines are super bright, in addition to OIII

**Comment by nrgolovich** [comment]
@karenyyng I guess if nothing else, we can cite the paper above and quote a redshift for this galaxy. It will be interesting to hear what David Sobral would have to say about this.

**Comment by wadawson** [comment]
@nrgolovich I am not sure what it means that there is Hd absorption and Hb emission. I think there is some relation that has something to say about this, though I can't remember what it is. 

As for their being little O[III] relative to Hb emission, I think it is just indicative of this being a star forming galaxy and not AGN etc.. See for example this figure from our CIZA spectral analysis paper:

![screen shot 2015-03-04 at 8 13 51 pm](https://cloud.githubusercontent.com/assets/3067471/6499185/b6c36e22-c2ab-11e4-95ed-d3995d552872.png)

**Comment by nrgolovich** [comment]
![hist](https://cloud.githubusercontent.com/assets/5620288/6499660/35cc44d4-c2b4-11e4-82b5-d4a6f7884094.png)

Just for reference. The galaxy appears to be moving to the northwest, mostly perpendicular from the direction of the western BCG
