### ISSUE TITLE
Redshift histogram bin width

### ISSUE THREAD

**Issue by nrgolovich** [karenyyng/MACSJ1752#2]
A lot of work is out there on optimal bin widths. A pretty common one used is Scott's rule:

h = 3.5*sigma/n^1/3

where h is the bin width, sigma is the sample std, n is the number of data points

With this rule, the histograms for the cluster wide redshift distributions look a lot different. Here is how I might have done it in the past:

![macsj1752_redshifthist_old](https://cloud.githubusercontent.com/assets/5620288/6502038/740f0d06-c2d4-11e4-9179-c85bc0ca5f28.png)

But here is what Scott's rule suggests:

![macsj1752_redshifthist_new](https://cloud.githubusercontent.com/assets/5620288/6502040/78bcbf88-c2d4-11e4-85cb-f3071a55a725.png)

What's better? 

My gut says that the second plot doesn't have the capability of showing features that may be present, but my eye sees things that are present in the smaller bins that aren't really as important as they look.

**Comment by karenyyng** [comment]
@nrgolovich you are seeing the bias-variance trade off

**Comment by karenyyng** [comment]
@nrgolovich do you know the underlying assumption of Scott's rule and why it suppresses the spikes? Also if every scientist just bin their data according to their gut feelings, you will see publications of the same set of data with very different looking histograms. There is a reason why people came up with histogramming rules. Not just for making plots look "good to the eye"

**Comment by nrgolovich** [comment]
It minimizes the integrated mean squared error.

**Comment by nrgolovich** [comment]
It's not as simple as just saying that and being done with the discussion though. We are dealing with dynamical systems, and if people look at that second histogram they'll think substructure might be buried; where as, if we presented the first histogram, and showed the BIC is lowest with a one-component Gaussian, it would be easier for them to convince themselves that their eyes are over fitting.

**Comment by karenyyng** [comment]
No minimizing the MISE is the aim, not the assumption.

**Comment by wadawson** [comment]
Scott's rule is not entirely correct here since I believe it assumes Gaussianity which might not be the case is a merger. I would lean more toward the first histogram and some statistical test.

**Comment by davidmwittman** [comment]
Agreed. Scott's rule assumes Gaussianity, so if we DID have two Gaussians
the sigma would be greatly overestimated and therefore the bin size too
fat. Why not use Bayesian blocks?

David Wittman
Associate Professor
Department of Physics
University of California, Davis

**Comment by nrgolovich** [comment]
At the end section 5 of http://biomet.oxfordjournals.org/content/66/3/605.full.pdf+html they discuss the use of Scott's rule on bimodal data. It works pretty well when the two Gaussians aren't too far apart. Once they are separated too much though, it over smooths.

**Comment by wadawson** [comment]
I doubt we will be dealing with distributions that are separated by more than 2x their variance. Or if we are then it should be obvious from almost any histogram that we are dealing with two Gaussians and shouldn't use this method.

**Comment by karenyyng** [comment]
@nrgolovich To be clear, I never thought Scott's rule may be better in this scenario. And yes Scott's rule assumes one big Gaussian distribution.  @wadawson  is right that the data show a mixture of Gaussian so Scott's rule is not appropriate. @davidmwittman 's suggestion of the use of Bayesian blocks is completely reasonable but in the past when I used Bayesian blocks, the block width can get very uneven i.e. the implemented version of Bayesian block in astroML doesn't seem very stable. I actually suggest using Knuth rule in the astroML library that is more stable. Knuth rule might not give you histogram that looks drastically different than the first histogram, but as scientists we should take caution about making arbitrary decisions about presenting our data. http://www.astroml.org/examples/algorithms/plot_bayesian_blocks.html

**Comment by nrgolovich** [comment]
The data doesn't show a mixture of multiple Gaussians, it shows that it is best modeled by a single Gaussian. This is why I thought Scott's rule might be appropriate here:

![gmm_select_1d_clustz](https://cloud.githubusercontent.com/assets/5620288/6520258/e6e994b6-c376-11e4-9f07-640c1333075f.png)

Readers have the basic assumption about mergers that they are _supposed_ to be a mixture of Gaussians, and I guess they are, but that would be evident if the LOS velocity difference was large, but that is not the case for this system, and most other radio relic systems that we have. 

I'm just worried that readers will think we are hiding the bimodality by making bins big, but conversely I'm worried that they will read too much into sub-structure if we make the bins small.

**Comment by davidmwittman** [comment]
Just brainstorming here: one thing some people do is put a whisker for each
galaxy along the bottom of the histogram, so readers can see it completely
unsmoothed. Another option might be KDE with adaptive kernel.

David Wittman
Associate Professor
Department of Physics
University of California, Davis

**Comment by wadawson** [comment]
I like the whisker idea. Let's do that and just make a histogram that looks ascetically pleasing to whoever makes it and has a useful bin width (e.g. some multiple of 50 km/s).

Let's forget all of this ideal bin width stuff. We never use binned histograms for any analysis, so I don't think it is worth the effort or debate.

**Comment by nrgolovich** [comment]
Sounds reasonable to me.
