### ISSUE TITLE
GMM has a hard time with the orientation of our masks in the spectroscopic survey

### ISSUE THREAD

**Issue by nrgolovich** [karenyyng/MACSJ1752#3]
This raises a couple issues with the GMM code as it stands for the larger sample. How can we inform the code to be robust against targeting, and how readily should we be willing to waive our hands against something like the BIC telling us one thing, but us believing something else. 

![gmm_select_3d_clustz](https://cloud.githubusercontent.com/assets/5620288/6516463/f999f3c4-c346-11e4-98e7-ba188bb0b6da.png)

2 component full model:

![gmmtriangle_2full](https://cloud.githubusercontent.com/assets/5620288/6516467/044d2444-c347-11e4-8210-adc162d45bb8.png)

2 component diag model:

![gmmtriangle_2diag](https://cloud.githubusercontent.com/assets/5620288/6516469/0906c7d8-c347-11e4-9a54-d680d16486d0.png)

**Comment by karenyyng** [comment]
Even if you have a perfect algorithm, it won't work on insufficient data.
